defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "ar"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "default-ar" # overrides previous default layout
      author: ""
  -
    scope:
      path: "en"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "default-en" # overrides previous default layout
      author: ""

url:

sass:
  sass_dir: _sass
  style: compressed

exclude: [html.iml,meem dev.iml,meem digital bank.iml,webchat-form.html,webchat-meem.js,webchat-working.js]

excerpt_separator: ""
